root = "."

[build]
cmd = "go build -o /tmp/main ./cmd/api"
bin = "/tmp/main"
full_bin = "/tmp/main"
include_ext = ["go", "toml"]
exclude_dir = ["vendor"]

[log]
level = "debug"

[misc]
clean_on_exit = true
