version: '3.8'

services:
  # Database Service (PostgreSQL)
  db:
    image: postgres:14-alpine
    container_name: spark-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # This persists the database data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Service (Our Go App)
  api:
    container_name: spark-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      db:
        condition: service_healthy # Wait for the DB to be ready before starting
    env_file:
      - .env

volumes:
  postgres_data: # Defines the volume used by the db service