# Use the official Golang image
FROM golang:1.24-alpine

# Set the working directory
WORKDIR /app

# Install air for live reloading
RUN go install github.com/air-verse/air@latest

# Copy go module files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the source code
COPY . .

# Command to run air
CMD ["air", "-c", ".air.toml"]
