# render.yml
databases:
  - name: spark-db
    databaseName: sparkdb
    user: sparkuser
    plan: free # Or your desired plan, e.g., "starter"

services:
  - type: web
    name: spark-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health # Add a health check endpoint to your app
    envVars:
      - key: API_PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: spark-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # Render will generate a secure secret
    secretFiles:
      - name: key-json
        mountPath: /app/key.json # Mount the secret file in your app
        content: |
          # Paste your KEY_JSON content here in the Render dashboard
          # It's recommended to add this via the Render dashboard
          # instead of hardcoding it in the render.yml file.
          # For initial setup, you can paste the content from your .env here.
          ${KEY_JSON}